---
# Main entrypoint for node roles

- name: Make variables for nodes
  ansible.builtin.import_tasks: node_variables.yml

- name: Create node directory
  become: true
  ansible.builtin.file:
    path: "{{ node_config_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "u=rwX,g=rwX,o=rX"

- name: Provision networking
  ansible.builtin.import_tasks: networking.yml

- name: Provision Podman
  tags: [podman]
  when: node_podman
  ansible.builtin.import_tasks: podman.yml

- name: Provision QEMU
  tags: [qemu]
  when: node_qemu
  ansible.builtin.import_tasks: qemu.yml

- name: Install QEMU VMs
  tags: [qemu]
  ansible.builtin.include_tasks: qemu-vm.yml
  when: node_qemu_vms | default(false) | bool
  loop: "{{ node_qemu_vms | default([]) }}"
  loop_control:
    loop_var: vm

- name: Install smoke test
  tags: [qemu, podman]
  when: node_smoke_test and node_podman and node_qemu
  ansible.builtin.import_tasks: smoke_test.yml
