---
# Deploy sample VM and container for sanity.

- name: Install smoke test VM
  ansible.builtin.include_tasks: qemu-vm.yml
  vars:
    vm:
      name: smoke
      src: "{{ node_smoke_test_qemu_src_vm }}"

- name: Install smoke test container
  block:

    - name: Make web root
      become: true
      ansible.builtin.file:
        state: directory
        path: "/tmp/webroot"
        mode: "u=rwX,g=rwX,o=rX"

    - name: Make web index
      become: true
      ansible.builtin.template:
        dest: /tmp/webroot/index.html
        src: smoke-web-index.html.j2
        mode: 'u=rw,g=rw,o=r'

    - name: Run web container
      containers.podman.podman_container:
        name: smoke-nginx
        image: docker.io/nginx
        state: started
        recreate: true
        rm: true
        volumes:
          - /tmp/webroot:/usr/share/nginx/html
        # generate_systemd:

# TODO: Try create macvlan network on the bridge?
